# Generated by Django 3.2.5 on 2021-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
