# Generated by Django 3.2.5 on 2021-07-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0003_option_question_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='select_test',
        ),
    ]
