# Generated by Django 3.2.5 on 2021-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0005_test_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
