# Generated by Django 3.2.5 on 2021-07-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0006_alter_test_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img_question',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='select_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='que', to='quizportal.test'),
        ),
    ]
