# Generated by Django 3.2.5 on 2021-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0007_auto_20210715_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_question',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
