# Generated by Django 3.2.5 on 2021-07-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0008_auto_20210715_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='select_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opts', to='quizportal.question'),
        ),
    ]
