# Generated by Django 3.2.5 on 2021-07-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0009_alter_option_select_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='omr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omr_ques', to='quizportal.question')),
            ],
        ),
    ]
