# Generated by Django 3.2.5 on 2021-07-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal', '0011_rename_question_omr_omr_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='omr',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizportal.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='omr',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizportal.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='omr',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizportal.option'),
        ),
    ]
